### ISSUE TITLE
When using Firefox, pressing enter in a pop-up textfield will go to a page which only says "true"

### ISSUE THREAD

**Issue by Bertware** [bang-olufsen/create#118]
I was able to reproduce this bug multiple times on Firefox 82.0.2 on Windows 10. I could not recreate the issue on Chrome or Edge.

- Setup a new HifiberryOS installation using Firefox
- Configure the network
- When asked about a name, click `Change name`
- Enter a name
- Press enter while the text field is still active

You are now on a page which only shows `true`

Pressing the okay/check mark in the dialog closes the dialog and saves the value, behaving as intended.

![Step 1](https://user-images.githubusercontent.com/1094793/97750152-8f162b00-1af0-11eb-938a-5e1fd5ef7475.png)
![Step 2](https://user-images.githubusercontent.com/1094793/97750398-fdf38400-1af0-11eb-8f01-4fb18d65d755.png)
![Step 3](https://user-images.githubusercontent.com/1094793/97750187-9f2e0a80-1af0-11eb-8266-35c9d3b2b70d.png)

**Comment by Bertware** [comment]
This also happens in other instances of the same popup, such as the "enter server ip" popup for Snapcast.

**Comment by tuomashamalainen** [comment]
Thanks for bringing this issue to my attention. Firefox seems to deal with form submit actions a bit differently than other browsers I frequently test, but I have found a fix and it will be included in the next update.

Best,
Tuomas from Bang & Olufsen

**Comment by tuomashamalainen** [comment]
Closing this, the fix should've been live for a while now.
