### ISSUE TITLE
Feature Request: Add PWA functionality (service worker, offline page, maskable icons etc.)

### ISSUE THREAD

**Issue by lorenz-h** [bang-olufsen/create#127]
It would be great if you could make the UI properly installable as a progressive web app on mobile and desktop devices. This should only require a service worker, a maskable icon and some tweaks to the manifest. If there is some interest, I would be happy to create a PR.

**Comment by tuomashamalainen** [comment]
Hi Lorenz and sorry for taking the time to respond,

this is definitely something I would be more than happy to add, as we already support running the UI in standalone mode on iOS devices (launches from the home screen and runs without Safari chrome). That existing feature would probably also benefit from this new initiative with barebones offline functionality.

If any new visual assets are needed, I can provide those no problem.

Best,
Tuomas from Bang & Olufsen

**Comment by lorenz-h** [comment]
Hey Tuomas, That sounds great. For reference this is the lighthouse PWA report for the current version :
![grafik](https://user-images.githubusercontent.com/32291082/103407126-a360bd80-4b5d-11eb-84d7-0fa4d1b7b28f.png)

**Comment by tuomashamalainen** [comment]
Thanks Lorenz, that's a pretty comprehensive report. Per my judgment, some of these warnings are not relevant in our use case (missing HTTPS – we don't want to have expiring certificates – and mobile loading speed in particular), as the UI is only ever meant to work over the local network.

**Comment by lorenz-h** [comment]
I absolutely agree Tuomas. Unfortunately, I believe the lack of https will mean users will not get an automatic "install as webapp" popup from browsers like chrome and firefox. It might make sense to add a designated button for triggering the installation manually from the UI.

**Comment by lorenz-h** [comment]
Unfortunately, it seems that Chrome does not not allow Service workers for sites that are not served via HTTPS ([reference](http://www.chromium.org/Home/chromium-security/prefer-secure-origins-for-powerful-new-features). The same is true for Firefox I believe. Therefore, It looks like we will not be able to add a service worker.
