### ISSUE TITLE
Sound > Speaker Preset not visible in UI

### ISSUE THREAD

**Issue by thk4711** [bang-olufsen/create#151]
The documentation is mentioning to go to Sound > Speaker Preset > Import Preset to activate speaker presets. I installed the latest version of hifiberry OS and there is no Speaker Presets Item under Sound. Since I want to use the beocreate card for a pair of CX 100 loudspeakers I somehow want to activate the preset in this repo.

**Comment by hifiberry** [comment]
Might be better to post this in the HiFiBerryOS forum is this is a HiFiBerryOS question. What sound card is detected?

**Comment by thk4711** [comment]
OK - I did that and here is what I found out - which might be useful for others:
the current release of HiFiBerryOS does not detect the beocreate card - this can be fixed like this:
[https://support.hifiberry.com/hc/en-us/community/posts/4406453186961-Beocreate-4ch-v1-2-new-installations-read-as-DAC-DSP](https://support.hifiberry.com/hc/en-us/community/posts/4406453186961-Beocreate-4ch-v1-2-new-installations-read-as-DAC-DSP)
Them you have to run the following command:
`dsptoolkit install-profile https://raw.githubusercontent.com/hifiberry/create/master/Beocreate2/beo-dsp-programs/beocreate-universal-10.xml
`
This will make it work again.
