### ISSUE TITLE
beocreate.server only announces IP address if on wifi

### ISSUE THREAD

**Issue by ingotee** [bang-olufsen/create#34]
https://github.com/bang-olufsen/create/blob/d79342c2d4beb634e68237a362fbcada7ab0ae1d/beocreate-server.js#L652

If the system is connected via ethernet only, there is no announcement.

**Comment by tuomashamalainen** [comment]
Currently the system is geared very much towards Wi-Fi-only operation as we imagine that's how most people will have it set up, and is not very smart about wired networks (to clarify, Raspbian obviously fully supports them – our server is at fault). This, and the network setup features in general, will need to be improved.

**Some backstory:** Android doesn't appear to support local hostnames in its browser, so this feature was created as a band-aid to that issue. We're hoping to retire the voice announcement feature as soon as there's a reliable way to connect to a headless BeoCreate system from Android devices without the need to enter the IP address. This works with Apple devices, so if we detect that a device connected via the local hostname, we disable the voice announcements as they are not necessary.

**Comment by tuomashamalainen** [comment]
Vocal announcement of IP addresses has been removed in Beocreate 2. The system now also handles Ethernet connections much better.

To look up the IP address of the system for connecting from devices that don't support local hostnames, I recommend connecting it to a display via HDMI and checking the address in the HiFiBerryOS splash screen. I also recommend trying out Beocreate Connect, which should automatically find the system for you with Bonjour (improvements coming).
