### ISSUE TITLE
Request: Implement 2 volume control: volume and limit

### ISSUE THREAD

**Issue by hifiberry** [bang-olufsen/create#37]
Limit should be used to limit the maximum volume. No application should be allowed to overwrite this.

Both settings, limit and current volume should be adjustable via GUI

**Comment by tuomashamalainen** [comment]
Beocreate 2 introduces a master volume control to the user interface that's always synchronised with the ALSA volume control of the system and the DSP (if available). In addition, Beocreate 2 has separate volume limiters for Raspberry Pi and optical input with Beocreate 4-Channel Amplifier.
