### ISSUE TITLE
BeoVoxS802 ResultingResponses wrong file

### ISSUE THREAD

**Issue by utkunx** [bang-olufsen/create#52]
hi there, 
BeoVoxS802_ResultingResponses.pdf file  is actuality BeoVoxS802_Filters.pdf
so BeoVoxS802_ResultingResponses.pdf file is missing there.
Thanks.

**Comment by tuomashamalainen** [comment]
Thanks for reporting this, it has somehow completely flown under my radar. I will reach out to our acoustics department to provide the correct file.

**Comment by soooch** [comment]
Hi, I was wondering if there was any progress in finding this graphic?

**Comment by tuomashamalainen** [comment]
Hi both,

very sorry about the delay. Somehow I completely forgot about this. I just now sent an inquiry to our acousticians (so that I can't forget it this time). I'll update as soon as I hear back.

**Comment by tuomashamalainen** [comment]
Hey there,

I just received the correct resulting responses file from our acoustics department and have updated it accordingly. Enjoy (and sorry for the long delay again)!

Tuomas from Bang & Olufsen
