### ISSUE TITLE
"MaxListenersExceededWarning: Possible EventEmitter memory leak detected."

### ISSUE THREAD

**Issue by qerub** [bang-olufsen/create#64]
I'm running HiFiBerry OS 20191220 and after a multiple restarts of the sigmatcp service I got these error messages:

```
(node:447) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:256:17)
    at Socket.addListener (events.js:272:10)
    at Socket.Readable.on (_stream_readable.js:842:35)
    at Socket.onConnect (/opt/beocreate/beocreate_essentials/dsp.js:330:12)
    at Socket.emit (events.js:198:13)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1092:10)
(node:447) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 data listeners added. Use emitter.setMaxListeners() to increase limit
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 data listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:256:17)
    at Socket.addListener (events.js:272:10)
    at Socket.Readable.on (_stream_readable.js:842:35)
    at Socket.onConnect (/opt/beocreate/beocreate_essentials/dsp.js:331:12)
    at Socket.emit (events.js:198:13)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1092:10)
```

Looking at https://github.com/bang-olufsen/create/blob/d9c4833/beocreate_essentials/dsp.js#L330 I can see that — yes — there's is in fact a leak, since the event listeners are never unregistered.

**Comment by tuomashamalainen** [comment]
Thanks for this report, very helpful. I'll look into this issue.

**Comment by tuomashamalainen** [comment]
This was a dumb oversight on my part – the listeners should only be attached once, like `connect` and `error` already were. They have now been moved out of the onConnect function next to the other two.

The proposed very simple fix is now in the 2020-02 branch ([commit](https://github.com/bang-olufsen/create/commit/3bb19ff6efb26a2c26c51a92e3df07a4303ebd1e)) and will be included in the next release. Suggestions on further improvements are always appreciated.

**Comment by tuomashamalainen** [comment]
The update to Beocreate 2/HiFiBerryOS containing this fix has now entered distribution. If you still encounter the problem, please reopen this issue.
