### ISSUE TITLE
Setup does not set Hostname on Raspberry PI

### ISSUE THREAD

**Issue by heikotroetsch** [bang-olufsen/create#8]
After setup the hostname was not set properly. This resulted in the BeoCreate Setup Tool not finding the PI. After looking at the Websocket connection failures, it also did not show the tool connecting to the proper IP, even though i manually entered it.

**Comment by tuomashamalainen** [comment]
Have forgotten to close this – Beocreate 2, as a part of HiFiBerryOS, has addressed this issue.
