### ISSUE TITLE
Spotifyd panics with WireError(InvalidEnumValue(14))

### ISSUE THREAD

**Issue by andym** [bang-olufsen/create#9]
When attempting to use Spotify connect it dies after a few seconds with:

`[ERROR] Caught panic with message: called `Result::unwrap()` on an `Err` value: WireError(InvalidEnumValue(14))
`

I was using the "Release 3" of the Beocreate installer which installs untagged-2cb556328b5f57a0fe2b/spotifyd-2018-01-14-armv7.zip

See also:

https://support.hifiberry.com/hc/en-us/community/posts/360006109105-Error-in-Spotifyd?page=1#community_comment_360000310669

**Comment by qerub** [comment]
@tuomashamalainen: I think this issue can be closed since #10 was merged.

**Comment by tuomashamalainen** [comment]
Thanks @qerub. Somehow this was left lingering.
