### ISSUE TITLE
Hifiberry OS missing bluetooth function in kernel

### ISSUE THREAD

**Issue by heikotroetsch** [bang-olufsen/create#91]
The bluetooth adapter in /sys/class/bluetooth seems to be missing in the kernel.

```
# systemctl status bluetooth
● bluetooth.service - Bluetooth service
   Loaded: loaded (/usr/lib/systemd/system/bluetooth.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
Condition: start condition failed at Tue 2020-05-12 19:51:47 CEST; 2s ago
           └─ ConditionPathIsDirectory=/sys/class/bluetooth was not met
     Docs: man:bluetoothd(8)
```

**Comment by tuomashamalainen** [comment]
Hi Heiko,

thanks for your report. @hifiberry this is probably something you need to take care of in Buildroot?

Best,
Tuomas from Bang & Olufsen

**Comment by hifiberry** [comment]
There is already a HiFiBerry bug report https://github.com/hifiberry/hifiberry-os/issues/80 , I think this can be closed

**Comment by tuomashamalainen** [comment]
Alright, I'll close this up.
