### ISSUE TITLE
websockets are broken when behind a https reverse proxy

### ISSUE THREAD

**Issue by fizzyade** [bang-olufsen/create#93]
beo-comms.js incorrectly assumes that the server is running on http, when using a http/2 proxy (I use caddy) it attempts to open a non-secure websocket connection (ws://) which is prohibited as upgrades are not allowed.

The code should be modified to detect whether to use ws:// or wss:// connections.

**Comment by tuomashamalainen** [comment]
Thanks for your report, Adrian. This is a use case I hadn't considered, but I'll definitely implement the suggested fix.

Best,
Tuomas from Bang & Olufsen

**Comment by fizzyade** [comment]
Hi tuomas,

I probably only noticed it because I use caddy as my reverse proxy which gives you https + letsencrypt “for free”, i.e it’s basically zero conf.  As this is an internal system, I guess most people if they were using a reverse proxy would be using plain old http but caddy is designed around https.

By the way, was very impressed that I installed hifiberry os worked straight off the bat, I plugged in my hifiberry dac+ and within a few minutes I had my mini projector sending audio to my sonos beam via the dac+ and optical!  

I have another suggestion, but will open another ticket unless there’s already one for it.

**Comment by fizzyade** [comment]
This is going to sound stupid coming from a software developer....

But how do I update this to test it, I used the HifiBerryOS image.  I assume it's some sort of npm update or something?

**Comment by tuomashamalainen** [comment]
No stupid questions! 🙂

The system has a built-in, one-touch software update function. Go to General -> Software Update and it should show up. Then you can select "Update Now".

Let me know how this goes and if the issue has been resolved for you.
