### ISSUE TITLE
Integration

### ISSUE THREAD

**Issue by barjonas** [bang-olufsen/create#97]
I'm looking to integrate my Becreate device with my home automation system. Is there any supported API? I have found the websockets endpoint that the web interface uses, but I can't find a way to specify a protocol string from my home automation system (OpenHAB with Node-RED), so I can't use that for now. Are there REST endpoints hiding in there?

Initially, I'll I'm planning to integrate with the master volume. Later, it might be nice to force particular sources or toggle some other controls.

Hamish

**Comment by MDAR** [comment]
Can you share your node please?
