### ISSUE TITLE
MacOS: Building BeocreateConnect fails

### ISSUE THREAD

**Issue by tsanko** [bang-olufsen/create#99]
Using Node 12.18.1 LTS

9 warnings and 8 errors generated.
make: *** [Release/obj.target/drivelist/src/drivelist.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/XXXX/.nvm/versions/node/v12.18.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.5.0
gyp ERR! command "/Users/XXXX/.nvm/versions/node/v12.18.1/bin/node" "/Users/XXXX/.nvm/versions/node/v12.18.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/XXXX/develop/create/BeocreateConnect/node_modules/drivelist
gyp ERR! node -v v12.18.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN BeocreateConnect@0.3.0 No repository field.

**Comment by tuomashamalainen** [comment]
Judging by the log it looks to be an issue with building the drivelist module on your system, which is probably beyond my control (npm just takes the listed modules and tries to install them). I will attempt a fresh reinstall of the environment on my system at a later point, but I have no resolution for the issue at this time.

**Comment by tsanko** [comment]
/Users/XXXX/develop/create/BeocreateConnect/node_modules/electron/index.js:14
    throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')

A short research point that it may run 32-bit mode ... updated all packages to the latest (quite outdated in project) and compiles and ran. Problem solved.

**Comment by tuomashamalainen** [comment]
Alright, thanks for following up!
